[package]
name = "termi"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[lints]
workspace = true

# [lib]
# path = "src/main.rs"

[dependencies]
gpui.workspace = true
gpui_platform = { workspace = true, features = ["font-kit"] }
assets.workspace = true
anyhow.workspace = true
log.workspace = true
env_logger.workspace = true
theme.workspace = true
theme_settings.workspace = true
settings.workspace = true
workspace.workspace = true
terminal.workspace = true
# terminal_view.workspace = true
gpui-component-assets.workspace = true
gpui-component.workspace = true
