[package]
name = "settings_content"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[lints]
workspace = true

[lib]
path = "src/settings_content.rs"

[dependencies]
anyhow.workspace = true
gpui.workspace = true
serde.workspace = true
serde_json.workspace = true
futures.workspace = true
settings_macros.workspace = true
inventory.workspace = true
utils.workspace = true
log.workspace = true
theme.workspace = true
serde_json_lenient.workspace = true
strum.workspace = true
rust-embed.workspace = true
