[package]
name = "protocol"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[lints]
workspace = true

[lib]
path = "src/protocol.rs"

[dependencies]
anyhow.workspace = true
tokio.workspace = true
russh.workspace = true
aws-lc-rs = { workspace = true, features = ["prebuilt-nasm"] }
log.workspace = true
serde.workspace = true
uuid.workspace = true
